---
background:
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunA_0.h5'
   name: '2023 ZB Run A'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunB_0.h5'
   name: '2023 ZB Run B'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunC_0.h5'
   name: '2023 ZB Run C'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/ZB_RunD_0.h5'
   name: '2023 ZB Run D'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_0.h5'
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_1.h5'
   - '/eos/project/c/cicada-project/data/2023/Background/EZB0_RunC_2.h5'
   name: '2023 EZB Run C'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/test/phi_sliced.h5'
   name: 'Test Training Set (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/B_phi_sliced.h5'
   name: 'Training Set (wisc)'
   use: False
 - path:
   - '/eos/user/a/aji/CICADASectionedData/test/phi_sliced.h5'
   name: 'Test Training Set (lxplus eos)'
   use: False
 - path:
   - '/eos/user/a/aji/CICADASectionedData/h5/B_phi_sliced.h5'
   name: 'Training Set (lxplus eos)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/ZB_RunA_0.h5'
   name: '2023 ZB Run A (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/ZB_RunB_0.h5'
   name: '2023 ZB Run B (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/ZB_RunC_0.h5'
   name: '2023 ZB Run C (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/ZB_RunD_0.h5'
   name: '2023 ZB Run D (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/EZB0_RunC_0.h5'
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/EZB0_RunC_1.h5'
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Background/EZB0_RunC_2.h5'
   name: '2023 EZB Run C (wisc)'
   use: False
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/ZB_RunA_0.h5'
   name: '2023 ZB Run A (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/ZB_RunB_0.h5'
   name: '2023 ZB Run B (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/ZB_RunC_0.h5'
   name: '2023 ZB Run C (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/ZB_RunD_0.h5'
   name: '2023 ZB Run D (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/EZB0_RunC_0.h5'
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/EZB0_RunC_1.h5'
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Background/EZB0_RunC_2.h5'
   name: '2023 EZB Run C (lxplus afs)'
   use: True

signal:
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/SUEP.h5'
   name: 'SUEP'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/H_ToLongLived.h5'
   name: 'HtoLongLived'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/VBFHto2C.h5'
   name: 'VBHFto2C'
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/TT.h5'
   name: 'TT' 
   use: False
 - path:
   - '/eos/project/c/cicada-project/data/2023/Signal/SUSYGGBBH.h5'
   name: 'SUSYGGBBH'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Signal/SUEP.h5'
   name: 'SUEP (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Signal/H_ToLongLived.h5'
   name: 'HtoLongLived (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Signal/VBFHto2C.h5'
   name: 'VBHFto2C (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Signal/TT.h5'
   name: 'TT (wisc)'
   use: False
 - path:
   - '/afs/hep.wisc.edu/home/andrewji/public/CICADASectionedData/h5/Signal/SUSYGGBBH.h5'
   name: 'SUSYGGBBH (wisc)'
   use: False
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Signal/SUEP.h5'
   name: 'SUEP (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Signal/H_ToLongLived.h5'
   name: 'HtoLongLived (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Signal/VBFHto2C.h5'
   name: 'VBHFto2C (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Signal/TT.h5'
   name: 'TT (lxplus afs)'
   use: True
 - path:
   - '/afs/cern.ch/user/a/aji/public/CICADASectionedData/Signal/SUSYGGBBH.h5'
   name: 'SUSYGGBBH (lxplus afs)'
   use: True

exposure:
 training:
  - '/eos/project/c/cicada-project/data/2023/Signal/DummyOutliers-Training.h5'
 validation:
  - '/eos/project/c/cicada-project/data/2023/Signal/DummyOutliers-Validation.h5'
